name: "Lidl Price Scraper"
version: "1.0.0"
slug: "lidl_price_scraper"
description: "Sleduje ceny nářadí na e-shopu Lidl.cz a v aktuálním letáku, posílá je do Home Assistant"
url: ""
arch:
  - amd64
  - aarch64
init: true
startup: application
boot: auto
ingress: true
ingress_port: 8088
panel_icon: mdi:tag-outline
panel_title: "Lidl ceny"
hassio_api: true
services:
  - mqtt:want
options:
  scrape_interval_minutes: 180
  headless: true
  debug_scraper: false
schema:
  scrape_interval_minutes: int(15,1440)
  headless: bool
  debug_scraper: bool
